# Práctica 1 — Dataset 3: Barrios analíticos ↔ Census Tracts (Bronze ➜ Silver)

**Objetivo:** Leer el CSV de relación entre barrios analíticos y *ensus tracts desde bronze,
quedarnos con las columnas necesarias, validar la clave geográfica (`census_tract`) y persistir en silver como Parquet.

In [1]:
# ============================================================
# 0) Imports + SparkSession
# ============================================================
from pyspark.sql import SparkSession, functions as F, types as T
import os

spark = SparkSession.builder.getOrCreate()
spark.conf.set("spark.sql.session.timeZone", "UTC")

print("Spark version:", spark.version)

WARNING: Using incubator modules: jdk.incubator.vector
:: loading settings :: url = jar:file:/opt/spark/jars/ivy-2.5.3.jar!/org/apache/ivy/core/settings/ivysettings.xml
Ivy Default Cache set to: /opt/spark/ivy/cache
The jars for the packages stored in: /opt/spark/ivy/jars
org.apache.spark#spark-hadoop-cloud_2.13 added as a dependency
io.delta#delta-spark_2.13 added as a dependency
org.apache.iceberg#iceberg-spark-runtime-4.0_2.13 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-5d8ef414-5cc2-42d6-8be4-7a02294a2486;1.0
	confs: [default]
	found org.apache.spark#spark-hadoop-cloud_2.13;4.0.1 in central
	found org.apache.hadoop#hadoop-client-runtime;3.4.1 in central
	found org.apache.hadoop#hadoop-client-api;3.4.1 in central
	found org.xerial.snappy#snappy-java;1.1.10.7 in central
	found org.slf4j#slf4j-api;2.0.16 in central
	found com.google.code.findbugs#jsr305;3.0.0 in central
	found org.apache.hadoop#hadoop-aws;3.4.1 in central
	found org.wildfly.openssl#wildfly-openssl;2.2.5.Final in central
	found software.amazon.awssdk#bundle;2.25.53 in central
	found com.google.cloud.bigdataoss#gcs-connector;hadoop3-2.2.26 in central
	found joda-time#joda-time;2.13.0 in central
	found com.fasterxml.jackson.core#jackson-databind;2.18.2 in central
	found com.fasterxml.jackson.core#jackson-annotations;2.18.2 in central
	found com.fasterxml.jackson.core#jackson-core;2.18.2 in central
	found com.fasterxml.jackson.dataformat#jackson-dataformat-cbor;2.18.2 in central
	found org.apache.httpcomponents#httpclient;4.5.14 in central
	found org.apache.httpcomponents#httpcore;4.4.16 in central
	found commons-codec#commons-codec;1.17.2 in central
	found org.apache.hadoop#hadoop-azure;3.4.1 in central
	found com.microsoft.azure#azure-storage;7.0.1 in central
	found com.microsoft.azure#azure-keyvault-core;1.0.0 in central
	found org.apache.hadoop.thirdparty#hadoop-shaded-guava;1.3.0 in central
	found org.apache.hadoop#hadoop-cloud-storage;3.4.1 in central
	found org.apache.hadoop#hadoop-annotations;3.4.1 in central
	found org.apache.hadoop#hadoop-aliyun;3.4.1 in central
	found com.aliyun.oss#aliyun-sdk-oss;3.13.2 in central
	found org.jdom#jdom2;2.0.6.1 in central
	found com.aliyun#aliyun-java-sdk-core;4.5.10 in central
	found org.ini4j#ini4j;0.5.4 in central
	found io.opentracing#opentracing-api;0.33.0 in central
	found io.opentracing#opentracing-util;0.33.0 in central
	found io.opentracing#opentracing-noop;0.33.0 in central
	found com.aliyun#aliyun-java-sdk-ram;3.1.0 in central
	found com.aliyun#aliyun-java-sdk-kms;2.11.0 in central
	found org.codehaus.jettison#jettison;1.5.4 in central
	found org.apache.hadoop#hadoop-azure-datalake;3.4.1 in central
	found com.microsoft.azure#azure-data-lake-store-sdk;2.3.9 in central
	found org.apache.hadoop#hadoop-huaweicloud;3.4.1 in central
	found com.huaweicloud#esdk-obs-java;3.20.4.2 in central
	found com.jamesmurty.utils#java-xmlbuilder;1.2 in central
	found org.eclipse.jetty#jetty-util;11.0.24 in central
	found org.eclipse.jetty#jetty-util-ajax;11.0.24 in central
	found com.squareup.okhttp3#okhttp;3.12.12 in central
	found com.squareup.okio#okio;1.17.6 in central
	found io.delta#delta-spark_2.13;4.0.1 in central
	found io.delta#delta-storage;4.0.1 in central
	found org.antlr#antlr4-runtime;4.13.1 in central
	found org.apache.iceberg#iceberg-spark-runtime-4.0_2.13;1.10.1 in central
:: resolution report :: resolve 1416ms :: artifacts dl 36ms
	:: modules in use:
	com.aliyun#aliyun-java-sdk-core;4.5.10 from central in [default]
	com.aliyun#aliyun-java-sdk-kms;2.11.0 from central in [default]
	com.aliyun#aliyun-java-sdk-ram;3.1.0 from central in [default]
	com.aliyun.oss#aliyun-sdk-oss;3.13.2 from central in [default]
	com.fasterxml.jackson.core#jackson-annotations;2.18.2 from central in [default]
	com.fasterxml.jackson.core#jackson-core;2.18.2 from central in [default]
	com.fasterxml.jackson.core#jackson-databind;2.18.2 from central in [default]
	com.fasterxml.jackson.dataformat#jackson-dataformat-cbor;2.18.2 from central in [default]
	com.google.cloud.bigdataoss#gcs-connector;hadoop3-2.2.26 from central in [default]
	com.google.code.findbugs#jsr305;3.0.0 from central in [default]
	com.huaweicloud#esdk-obs-java;3.20.4.2 from central in [default]
	com.jamesmurty.utils#java-xmlbuilder;1.2 from central in [default]
	com.microsoft.azure#azure-data-lake-store-sdk;2.3.9 from central in [default]
	com.microsoft.azure#azure-keyvault-core;1.0.0 from central in [default]
	com.microsoft.azure#azure-storage;7.0.1 from central in [default]
	com.squareup.okhttp3#okhttp;3.12.12 from central in [default]
	com.squareup.okio#okio;1.17.6 from central in [default]
	commons-codec#commons-codec;1.17.2 from central in [default]
	io.delta#delta-spark_2.13;4.0.1 from central in [default]
	io.delta#delta-storage;4.0.1 from central in [default]
	io.opentracing#opentracing-api;0.33.0 from central in [default]
	io.opentracing#opentracing-noop;0.33.0 from central in [default]
	io.opentracing#opentracing-util;0.33.0 from central in [default]
	joda-time#joda-time;2.13.0 from central in [default]
	org.antlr#antlr4-runtime;4.13.1 from central in [default]
	org.apache.hadoop#hadoop-aliyun;3.4.1 from central in [default]
	org.apache.hadoop#hadoop-annotations;3.4.1 from central in [default]
	org.apache.hadoop#hadoop-aws;3.4.1 from central in [default]
	org.apache.hadoop#hadoop-azure;3.4.1 from central in [default]
	org.apache.hadoop#hadoop-azure-datalake;3.4.1 from central in [default]
	org.apache.hadoop#hadoop-client-api;3.4.1 from central in [default]
	org.apache.hadoop#hadoop-client-runtime;3.4.1 from central in [default]
	org.apache.hadoop#hadoop-cloud-storage;3.4.1 from central in [default]
	org.apache.hadoop#hadoop-huaweicloud;3.4.1 from central in [default]
	org.apache.hadoop.thirdparty#hadoop-shaded-guava;1.3.0 from central in [default]
	org.apache.httpcomponents#httpclient;4.5.14 from central in [default]
	org.apache.httpcomponents#httpcore;4.4.16 from central in [default]
	org.apache.iceberg#iceberg-spark-runtime-4.0_2.13;1.10.1 from central in [default]
	org.apache.spark#spark-hadoop-cloud_2.13;4.0.1 from central in [default]
	org.codehaus.jettison#jettison;1.5.4 from central in [default]
	org.eclipse.jetty#jetty-util;11.0.24 from central in [default]
	org.eclipse.jetty#jetty-util-ajax;11.0.24 from central in [default]
	org.ini4j#ini4j;0.5.4 from central in [default]
	org.jdom#jdom2;2.0.6.1 from central in [default]
	org.slf4j#slf4j-api;2.0.16 from central in [default]
	org.wildfly.openssl#wildfly-openssl;2.2.5.Final from central in [default]
	org.xerial.snappy#snappy-java;1.1.10.7 from central in [default]
	software.amazon.awssdk#bundle;2.25.53 from central in [default]
	:: evicted modules:
	software.amazon.awssdk#bundle;2.24.6 by [software.amazon.awssdk#bundle;2.25.53] in [default]
	org.eclipse.jetty#jetty-util-ajax;9.4.53.v20231009 by [org.eclipse.jetty#jetty-util-ajax;11.0.24] in [default]
	org.wildfly.openssl#wildfly-openssl;1.1.3.Final by [org.wildfly.openssl#wildfly-openssl;2.2.5.Final] in [default]
	com.squareup.okhttp3#okhttp;3.14.2 by [com.squareup.okhttp3#okhttp;3.12.12] in [default]
	com.squareup.okio#okio;1.17.2 by [com.squareup.okio#okio;1.17.6] in [default]
	com.squareup.okio#okio;1.15.0 by [com.squareup.okio#okio;1.17.6] in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   54  |   0   |   0   |   6   ||   48  |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-5d8ef414-5cc2-42d6-8be4-7a02294a2486
	confs: [default]
	0 artifacts copied, 48 already retrieved (0kB/20ms)
26/03/03 11:42:37 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/03/03 11:42:38 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
26/03/03 11:42:38 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
26/03/03 11:42:50 ERROR Inbox: Ignoring error
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:53)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:342)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:36)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:132)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:131)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:700)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:699)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:739)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:141)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:104)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:216)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:101)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:76)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:42)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@80e07f457085:37625
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:151)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:147)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:504)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:504)
	at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:335)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:278)
	at scala.concurrent.Promise.trySuccess(Promise.scala:99)
	at scala.concurrent.Promise.trySuccess$(Promise.scala:99)
	at scala.concurrent.impl.Promise$DefaultPromise.trySuccess(Promise.scala:104)
	at org.apache.spark.rpc.netty.NettyRpcEnv.onSuccess$1(NettyRpcEnv.scala:228)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5(NettyRpcEnv.scala:242)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5$adapted(NettyRpcEnv.scala:241)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:278)
	at scala.concurrent.Promise.complete(Promise.scala:57)
	at scala.concurrent.Promise.complete$(Promise.scala:56)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:104)
	at scala.concurrent.Promise.success(Promise.scala:91)
	at scala.concurrent.Promise.success$(Promise.scala:91)
	at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:104)
	at org.apache.spark.rpc.netty.LocalNettyRpcCallContext.send(NettyRpcCallContext.scala:50)
	at org.apache.spark.rpc.netty.NettyRpcCallContext.reply(NettyRpcCallContext.scala:32)
	at org.apache.spark.rpc.netty.RpcEndpointVerifier$$anonfun$receiveAndReply$1.applyOrElse(RpcEndpointVerifier.scala:31)
	... 8 more
26/03/03 11:42:50 WARN Executor: Issue communicating with driver in heartbeater
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:53)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:342)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:101)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:85)
	at org.apache.spark.storage.BlockManagerMaster.registerBlockManager(BlockManagerMaster.scala:81)
	at org.apache.spark.storage.BlockManager.reregister(BlockManager.scala:669)
	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1296)
	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:307)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1937)
	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:53)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:342)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:36)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:132)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:131)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:700)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:699)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:739)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:141)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:104)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:216)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:101)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:76)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:42)
	... 3 more
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@80e07f457085:37625
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:151)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:147)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:504)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:504)
	at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:335)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:278)
	at scala.concurrent.Promise.trySuccess(Promise.scala:99)
	at scala.concurrent.Promise.trySuccess$(Promise.scala:99)
	at scala.concurrent.impl.Promise$DefaultPromise.trySuccess(Promise.scala:104)
	at org.apache.spark.rpc.netty.NettyRpcEnv.onSuccess$1(NettyRpcEnv.scala:228)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5(NettyRpcEnv.scala:242)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5$adapted(NettyRpcEnv.scala:241)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)

Spark version: 4.0.1

In [2]:
# Funcion para facilitar visualización
from IPython.display import display
import pandas as pd
pd.set_option("display.max_columns", None)  # muestra todas las columnas

def display_df(
    df,
    n=10,
    columns=None,
    sort_by=None,
    ascending=False
):
    """
    Visualiza un DataFrame de Spark en Jupyter de forma similar a Databricks display().

    Parámetros:
    - df: DataFrame de Spark
    - n: número máximo de filas a mostrar (default: 20)
    - columns: lista opcional de columnas a mostrar
    - sort_by: columna opcional para ordenar
    - ascending: orden ascendente o descendente
    """

    if columns:
        df = df.select(columns)

    if sort_by:
        df = df.orderBy(sort_by, ascending=ascending)

    pdf = df.limit(n).toPandas()
    display(pdf)

In [3]:
# ============================================================
# 0.1) Configuración MinIO (S3A)
# ============================================================
MINIO_ENDPOINT = os.getenv("MINIO_ENDPOINT", "http://minio:9000")
MINIO_ACCESS_KEY = os.getenv("MINIO_ACCESS_KEY", "minioadmin")
MINIO_SECRET_KEY = os.getenv("MINIO_SECRET_KEY", "minioadmin")
MINIO_USE_SSL = os.getenv("MINIO_USE_SSL", "false").lower() == "true"

hconf = spark._jsc.hadoopConfiguration()
hconf.set("fs.s3a.endpoint", MINIO_ENDPOINT)
hconf.set("fs.s3a.access.key", MINIO_ACCESS_KEY)
hconf.set("fs.s3a.secret.key", MINIO_SECRET_KEY)
hconf.set("fs.s3a.path.style.access", "true")
hconf.set("fs.s3a.connection.ssl.enabled", "true" if MINIO_USE_SSL else "false")
hconf.set("fs.s3a.aws.credentials.provider", "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider")
hconf.set("fs.s3a.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem")

print("MINIO_ENDPOINT =", MINIO_ENDPOINT)

MINIO_ENDPOINT = http://minio:9000

## 1) Lectura desde Bronze (sin inferir esquema)

Leemos desde la carpeta del dataset.

In [4]:
BRONZE_PATH = "s3a://bronze/2020_census_tracts_to_neighborhoods_20251208.csv/"

df_raw = (
    spark.read
        .option("header", True)
        .option("inferSchema", "false")
        .csv(BRONZE_PATH)
)

df_raw.printSchema()
display_df(df_raw, n=5)

root
 |-- the_geom: string (nullable = true)
 |-- object_id: string (nullable = true)
 |-- state_fp: string (nullable = true)
 |-- county_fp: string (nullable = true)
 |-- tractce: string (nullable = true)
 |-- name: string (nullable = true)
 |-- neighborhoods_analysis_boundaries: string (nullable = true)
 |-- data_loaded_at: string (nullable = true)
 |-- sup_dist_2012: string (nullable = true)
 |-- sup_dist_2022: string (nullable = true)
 |-- data_as_of: string (nullable = true)
 |-- geoid: string (nullable = true)

,the_geom,object_id,state_fp,county_fp,tractce,name,neighborhoods_analysis_boundaries,data_loaded_at,sup_dist_2012,sup_dist_2022,data_as_of,geoid
0,MULTIPOLYGON (((-122.37276211607421 37.7455051...,242,06,075,980900,9809,Bayview Hunters Point,2022 Jul 08 02:12:00 PM,10,10,2022 Jul 08 09:09:48 PM,06075980900
1,MULTIPOLYGON (((-122.36519199065519 37.7337298...,241,06,075,980600,9806,Bayview Hunters Point,2022 Jul 08 02:12:00 PM,10,10,2022 Jul 08 09:09:48 PM,06075980600
2,MULTIPOLYGON (((-122.40666500014143 37.7192149...,240,06,075,980501,9805.01,McLaren Park,2022 Jul 08 02:12:00 PM,10,10,2022 Jul 08 09:09:48 PM,06075980501
3,MULTIPOLYGON (((-123.00359900126116 37.6932479...,239,06,075,980401,9804.01,The Farallones,2022 Jul 08 02:12:00 PM,1,4,2022 Jul 08 09:09:48 PM,06075980401
4,MULTIPOLYGON (((-122.38528200051307 37.7402399...,226,06,075,061200,612,Bayview Hunters Point,2022 Jul 08 02:12:00 PM,10,10,2022 Jul 08 09:09:48 PM,06075061200

## 2) Seleccionar y renombrar columnas en un solo paso

- `neighborhoods_analysis_boundaries` → `analysis_neighborhood`
- `geoid` → `census_tract`

In [5]:
df = df_raw.select(
    F.col("neighborhoods_analysis_boundaries").alias("analysis_neighborhood"),
    F.col("geoid").alias("census_tract"),
)

df.printSchema()
display_df(df, n=10)

root
 |-- analysis_neighborhood: string (nullable = true)
 |-- census_tract: string (nullable = true)

   analysis_neighborhood census_tract
0  Bayview Hunters Point  06075980900
1  Bayview Hunters Point  06075980600
2           McLaren Park  06075980501
3         The Farallones  06075980401
4  Bayview Hunters Point  06075061200
5              Chinatown  06075061102
6              Chinatown  06075061101
7  Bayview Hunters Point  06075061000
8       Golden Gate Park  06075980300
9         Outer Richmond  06075047600

## 3) Validación de la clave geográfica `census_tract`

Comprobaciones requeridas:

1. Es de tipo **string**
2. Tiene longitud **11**
3. Conserva correctamente los **ceros a la izquierda**

En las siguientes celdas se realizan las comprobaciones y se muestran métricas para justificar el resultado.

In [6]:
from pyspark.sql.types import StringType

# 1) Tipo string
is_string = isinstance(df.schema["census_tract"].dataType, StringType)
print("¿census_tract es string?:", is_string)

# 2) Longitud 11
invalid_len = df.filter(F.length("census_tract") != 11).count()
print("Filas con longitud != 11:", invalid_len)

# 3) Ceros a la izquierda:
# Si la columna se hubiese leído como numérica, valores como 06075010101 perderían el 0 inicial.
# Medimos cuántos valores empiezan por '0' y además verificamos que son 11 dígitos.
starts_with_zero = df.filter(F.col("census_tract").startswith("0")).count()
not_11_digits = df.filter(~F.col("census_tract").rlike(r"^\d{11}$")).count()

print("Filas cuyo census_tract empieza por '0':", starts_with_zero)
print("Filas cuyo census_tract NO cumple ^\d{11}$:", not_11_digits)

# Muestra ejemplos (incluye potencialmente valores con 0 inicial)
display_df(df.select("census_tract").orderBy("census_tract"), n=10)

¿census_tract es string?: True
Filas con longitud != 11: 0
Filas cuyo census_tract empieza por '0': 242
Filas cuyo census_tract NO cumple ^\d{11}$: 0

  census_tract
0  06075010101
1  06075010102
2  06075010201
3  06075010202
4  06075010300
5  06075010401
6  06075010402
7  06075010500
8  06075010600
9  06075010701

**Explicación (completa tras ejecutar):**

- **Tipo:** `True` → se mantiene como `string` (al leer CSV sin inferir esquema).
- **Longitud:** `0` filas con longitud distinta de 11 → **correcto** (todas tienen 11 dígitos).
- **Ceros a la izquierda:** hay `242` valores que empiezan por `0` y `0` filas que no cumplen `^\d{11}$` → los ceros se han preservado.

Conclusión: `census_tract` es una clave geográfica válida para unir con otros datasets a nivel de Census Tract.

## 4) Escritura en Silver (Parquet)

Persistimos el resultado en:

- `silver/sf_neighborhoods_census_tracts/`

In [7]:
SILVER_PATH = "s3a://silver/sf_neighborhoods_census_tracts/"

(
    df.write
      .mode("overwrite")
      .parquet(SILVER_PATH)
)

df_check = spark.read.parquet(SILVER_PATH)
print("Filas en silver:", df_check.count())
df_check.printSchema()

26/03/03 11:43:00 WARN S3ABlockOutputStream: Application invoked the Syncable API against stream writing to sf_neighborhoods_census_tracts/_temporary/0/_temporary/attempt_202603031142595548039495050977236_0013_m_000000_10/part-00000-ed3c42dd-1864-46e7-9e90-4652524e6887-c000.snappy.parquet. This is Unsupported

Filas en silver: 242
root
 |-- analysis_neighborhood: string (nullable = true)
 |-- census_tract: string (nullable = true)

## 5) Preguntas analíticas

### i) ¿Cuántos census tracts distintos hay?

In [8]:
n_tracts = df.select("census_tract").distinct().count()
print(n_tracts)

242

Hay 242 census tracts distintos.

### ii) ¿Cuántos barrios analíticos distintos hay?

In [9]:
n_neigh = df.select("analysis_neighborhood").distinct().count()
print(n_neigh)

42

Hay 42 barrios analíticos distintos.

### iii) ¿Puede un barrio estar asociado a varios census tracts?

In [10]:
neigh_stats = (
    df.groupBy("analysis_neighborhood")
      .agg(F.countDistinct("census_tract").alias("n_tracts"))
)

neigh_with_many = neigh_stats.filter(F.col("n_tracts") > 1).count()
max_tracts_per_neigh = neigh_stats.agg(F.max("n_tracts").alias("max_n_tracts")).collect()[0]["max_n_tracts"]

print(neigh_with_many)
print(max_tracts_per_neigh)

34
17

Si, hay 34 barrios con más de 1 census tract (el número máximo de tracts asociados a un mismo barrio es de 17).

### iv) ¿Puede un census tract pertenecer a varios barrios?

In [11]:
tract_stats = (
    df.groupBy("census_tract")
      .agg(F.countDistinct("analysis_neighborhood").alias("n_neigh"))
)

tracts_with_many = tract_stats.filter(F.col("n_neigh") > 1).count()
max_neigh_per_tract = tract_stats.agg(F.max("n_neigh").alias("max_n_neigh")).collect()[0]["max_n_neigh"]

print(tracts_with_many)
print(max_neigh_per_tract)

0
1

No. Hay 0 census tracts asociados a más de un barrio (y obviamente el máximo de barrios por tract es 1).

### v) Justifica brevemente qué tipo de relación existe entre barrios analíticos y census tracts

Usando los resultados de (iii) y (iv) para justificar si la relación es:
- 1 a 1
- 1 a N
- N a 1
- N a M

In [12]:
# Calculamos indicadores booleanos
can_neigh_have_many_tracts = True #Los vecindarios pueden tener mas de un census tract como hemos visto en el ejercicio iii.)
can_tract_have_many_neigh = False #Los census tract solo pueden pertenecer a un barrio, como hemos visto en el ejercicio iv.)

#Viendo todos los casos posibles, vamos a ver cual sale como verídico.
if can_neigh_have_many_tracts and can_tract_have_many_neigh:
    relation = "N a M"
elif can_neigh_have_many_tracts and not can_tract_have_many_neigh:
    relation = "1 a N"
elif (not can_neigh_have_many_tracts) and can_tract_have_many_neigh:
    relation = "N a 1"
else:
    relation = "1 a 1"

print(relation)

1 a N

Tipo de relación: 1 a N (de *barrio* → *census tracts*). Segun las dos celdas anteriores, al haber 34 barrios que agrupan varios tracts, pero ningún tract pertenece a más de un barrio podemos decir que la relacion es de un barrio a muchos tracts. La lógica del codigo de arriba es exactamente la misma que la descrita en esta celda.